### ISSUE TITLE
Oblige 7.666

### ISSUE THREAD

**Issue by brandleesee** [CloudOfShame/BrutalOblige#9]
Where do I find the option for Brutal monsters in Oblige menu? 
(this in light that new version of Oblige has revamped the UI)
Adding to Addon List is done.

Thanks.

**Comment by CloudOfShame** [comment]
In the far right hand list of options, there should be one labeled "Brutal Doom Monster Control". Check the box and it will expand to let you set your preferences on a per monster basis.

**Comment by brandleesee** [comment]
I have no such option at far right.
![screenshot 1505584702](https://user-images.githubusercontent.com/12674437/30514649-bfce8c88-9b19-11e7-9e08-6e0afcc5c1d1.png)

The following is to show that addon is checked.
Of course, I restarted Oblige....
![oblige](https://user-images.githubusercontent.com/12674437/30514664-00e0d104-9b1a-11e7-8e4c-76a388cd90f1.png)

**Comment by brandleesee** [comment]
My mistake was that I had repackaged the .pk3 file incorrectly.

Thus, in order to fully benefit from your mod, one has to set the following in the first column:
Game Settings --> Game --> Brutal Doom
This will unlock all B.D. options on the far right column.

Meanwhile, I see that doing the above I get two options for a Smaller Spiderdemon with different onhover explanatory notes.

![screenshot 1505587960](https://user-images.githubusercontent.com/12674437/30515027-31ca45e6-9b21-11e7-9ebb-a6eb6f129ed8.png)

Text for Skulltag option cannot be completely read:
There are much more that have their text cropped out from the left side of the last column.
![screenshot 1505588202](https://user-images.githubusercontent.com/12674437/30515069-baf6e5b8-9b21-11e7-9b79-2cc5ae88c059.png)

On the other hand, Project Brutality carries on further than the limit imposed on the right side of the last column:
![screenshot 1505588475](https://user-images.githubusercontent.com/12674437/30515113-56e3499e-9b22-11e7-981e-f55dbd6e043e.png)

**Comment by CloudOfShame** [comment]
The Smaller Spiderdemon script changed name in the last Oblige update, hence my replacement started appearing as a separate option. Fixed in commit f3255355e435aa87976efac5251d751c43011925.

I've moved some of the overunning options onto two lines. This means they can all be read but doesn't look particularly good. I'm not really sure how to work around this other than comming up with shorter names for things, but then it might not be clear what those options do.

**Comment by brandleesee** [comment]
> f325535 
Thanks!

> coming up with shorter names 
I second this. For clarity's sake, add onhover descriptions.
Truth be told there are several things that I still do not know what they do on switching on or their effect during gameplay.
